### ISSUE TITLE
ZeroDivisionError: division by zero 

### ISSUE THREAD

**Issue by jrey9402** [XDynames/SAI-app#13]
Hi!
Im running the SAI app in  Ubuntu 20.04.5 LTS (GNU/Linux 5.15.79.1-microsoft-standard-WSL2 x86_64).

When I analyze a group of images, at the end of the analysis it returns this error:  

ZeroDivisionError: division by zero

Traceback:
File "/home/stomata/.local/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/home/stomata/SAI-app/main.py", line 38, in <module>
    main()
File "/home/stomata/SAI-app/main.py", line 16, in main
    maybe_do_inference()
File "/home/stomata/SAI-app/app/inference.py", line 63, in maybe_do_inference
    maybe_do_inference_on_all_images_in_folder()
File "/home/stomata/SAI-app/app/inference.py", line 114, in maybe_do_inference_on_all_images_in_folder
    do_inference_on_all_images_in_folder()
File "/home/stomata/SAI-app/app/inference.py", line 201, in do_inference_on_all_images_in_folder
    remove_outliers_from_records()
File "/home/stomata/SAI-app/inference/post_processing.py", line 168, in remove_outliers_from_records
    remove_outliers(record, filename)
File "/home/stomata/SAI-app/inference/post_processing.py", line 199, in remove_outliers
    remove_bounding_box_outliers(record)
File "/home/stomata/SAI-app/inference/post_processing.py", line 211, in remove_bounding_box_outliers
    remove_bounding_box_height_outliers(record, near_edge_indices)
File "/home/stomata/SAI-app/inference/post_processing.py", line 228, in remove_bounding_box_height_outliers
    to_remove = find_outlier_bbox_indices(
File "/home/stomata/SAI-app/inference/post_processing.py", line 277, in find_outlier_bbox_indices
    if is_less_than_half_of_average_size(
File "/home/stomata/SAI-app/inference/post_processing.py", line 291, in is_less_than_half_of_average_size
    average_size = sum(valid_sizes) / len(valid_sizes)

What could be happening (im not an advance user)?

**Comment by XDynames** [comment]
Yeah this is something I should be covering better.

In this case the list containing the valid bounding boxes sizes is empty so `sum(valid_size) / len(valid_sizes) = 0/0`, which throws the division by zero error.

Non-technical answer is that SAI didn't make any valid detections on the images you fed it. Do you have any details about the images that you could share with me? Perhaps the species, resolution and camera calibration?

**Comment by jrey9402** [comment]
Could it be possible to add a function that ignores empty images? 
In some cases when I analyze a single image, SAI returns a valid result. Apparently, there are some images that do not contain stomata.

I am using Arabidopsis images with a resolution of 1920 x 1440, and cam correction of 885,18300 px/µm

The images con from Imprints, a similar method like this, but with glue https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8410313/

**Comment by XDynames** [comment]
Oh right! Yes this is not something that I anticipated, but very valid.

I will work on a solution and hopefully have something for you in a couple of days

Just as a side note, is this: 885,18300 px/µm, the same as 885.18300 px/µm?
The stoma will be a larger scale then what was used in training, but we have seen better results on larger scale than smaller so hopefully SAI will be able to help you out.

**Comment by XDynames** [comment]
Without thinking about it very much I think this should be enough to get you around the division by zero error.

When you have a terminal navigated to the directory SAI is in run `git checkout 13-images-with-no-stoma` to test out the fix.
It might not fix everything but if you could report back what happens I'd be grateful.

I might have to put together a little example dataset with some images with stoma and without to fully test it. I might be able to fake by chucking some Arabidopsis in with the Barley....

**Comment by jrey9402** [comment]
> 
> When you have a terminal navigated to the directory SAI is in run `git checkout 13-images-with-no-stoma` to test out the fix. It might not fix everything but if you could report back what happens I'd be grateful.
 
I tried, and this came out.

stomata@JRCCSamsung:~/SAI-app$ git checkout 13-images-with-no-stoma
error: pathspec '13-images-with-no-stoma' did not match any file(s) known to git

**Comment by XDynames** [comment]
Oh you might need to run ‘git pull’ first

**Comment by jrey9402** [comment]
Good, I will try with the same pictures again. 

stomata@JRCCSamsung:~/SAI-app$ git pull
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 8 (delta 6), reused 5 (delta 3), pack-reused 0
Unpacking objects: 100% (8/8), 659 bytes | 109.00 KiB/s, done.
From https://github.com/XDynames/SAI-app
 * [new branch]      13-images-with-no-stoma -> origin/13-images-with-no-stoma
Already up to date.
stomata@JRCCSamsung:~/SAI-app$ git checkout 13-images-with-no-stoma
Branch '13-images-with-no-stoma' set up to track remote branch '13-images-with-no-stoma' from 'origin'.
Switched to a new branch '13-images-with-no-stoma'

**Comment by XDynames** [comment]
Awesome looks like it checked out 
Let me know

**Comment by XDynames** [comment]
Did you have a chance to run your data through SAI with that change checkedout?

**Comment by jrey9402** [comment]
> Did you have a chance to run your data through SAI with that change checked-out?

Yes, It is working well now. The error didn't show up again. Thank!
