### ISSUE TITLE
warning and error...

### ISSUE THREAD

**Issue by NIES-Tsuda** [XDynames/SAI-app#15]
Dear Mr. James
I am a PC novice from Japan.
I would like to install StomaAI on my PC (Windows 11), but when I run "bash setup.sh" in the installation instructions, I get the following warning and error

"DEPRECATION: The HTML index page being used (https://download.pytorch.org/whl/torch_stable.html) is not a proper HTML 5 document. This is in violation of PEP 503 which requires these pages to be well-formed HTML 5 documents. Please reach out to the owners of this index page, and ask them Please reach out to the owners of this index page, and ask them to update this index page to a valid HTML 5 document. pip 22.2 will enforce this behaviour change. Discussion can be found at https://github.com/pypa/pip /issues/10825
ERROR: Could not find a version that satisfies the requirement torch==1.8.1+cpu (from versions: 1.11.0, 1.11.0+cpu, 1.11.0+cu102, 1.11.0+cu113, 1. 11.0+cu115, 1.11.0+rocm4.3.1, 1.11.0+rocm4.5.2, 1.12.0, 1.12.0+cpu, 1.12.0+cu102, 1.12.0+cu113, 1.12.0+cu116, 1.12.0+rocm5. 1.1, 1.12.1, 1.12.1+cpu, 1.12.1+cu102, 1.12.1+cu113, 1.12.1+cu116, 1.12.1+rocm5.0, 1.12.1+rocm5.1.1, 1.13.0, 1.13.0+cpu, 1.13.0+cu116, 1.13.0 +cu117, 1.13.0+cu117.with.pypi.cudnn, 1.13.0+rocm5.1.1, 1.13.0+rocm5.2, 1.13.1, 1.13.1+cpu, 1.13.1+cu116, 1.13.1+cu117, 1.13.1+cu117.with. pypi.cudnn, 1.13.1+rocm5.1.1, 1.13.1+rocm5.2, 2.0.0, 2.0.0+cpu, 2.0.0+cpu.cxx11.abi, 2.0.0+cu117, 2.0.0+cu117.with.pypi.cudnn, 2.0.0+cu118 2.0.0+rocm5.3, 2.0.0+rocm5.4.2)
ERROR: No matching distribution found for torch==1.8.1+cpu"

I have also checked the administrator of "https://download.pytorch.org/whl/torch_stable.html" but I can't figure it out.

If you know how I can install StomaAI, please let me know.

Best regards.

**Comment by XDynames** [comment]
Ah looks like they may have taken that binary off of pypip

Do you mind changing the version number in ‘requirements.txt’ of torch from ‘torch==1.8.1+cpu’ to ‘torch==1.11.0+cpu’ and re-run ‘bash setup.sh’?

**Comment by NIES-Tsuda** [comment]
Thanks!
There is no 'torch==1.8.1+cpu' in 'requirements.txt', and in 'setup.sh' 'torch==1.8. 1+cpu' to 'torch==1.11.0+cpu'. Then I get 'setup.sh: line 13: syntax error: unexpected end of file'. 13 is impossible to fix when Line is only up to 12.

**Comment by XDynames** [comment]
Ah right you are sorry - messaging from my phone

Umm I’m not 100% sure why changing the version number would induce the end of file exception.
Do you mind posting what ‘setup.sh’ looks like after editing the version number here?

**Comment by NIES-Tsuda** [comment]
if [[ "$OSTYPE" == "darwin"* ]]; then
pip3 install torch torchvision torchaudio
else
pip3 install --find-links https://download.pytorch.org/whl/torch_stable.html \
    torch==1.11.0+cpu \
    torchvision==0.9.1+cpu \
    torchaudio==0.8.1
fi
pip3 install git+https://github.com/facebookresearch/detectron2.git
pip3 install -r requirements.txt
pip3 install mask-to-polygons==0.0.2 --no-deps
pip3 install -e .

**Comment by XDynames** [comment]
Do the back slashes disappear because they are posted to GitHub or have they been removed somehow?

**Comment by NIES-Tsuda** [comment]
It looks like the backslash is gone because you pasted from Japanese software.
How about this

if [[ "$OSTYPE" == "darwin"* ]]; then
pip3 install torch torchvision torchaudio
else
pip3 install --find-links https://download.pytorch.org/whl/torch_stable.html \
    torch==1.11.0+cpu \
    torchvision==0.9.1+cpu \
    torchaudio==0.8.1
fi
pip3 install git+https://github.com/facebookresearch/detectron2.git
pip3 install -r requirements.txt
pip3 install mask-to-polygons==0.0.2 --no-deps
pip3 install -e .

**Comment by NIES-Tsuda** [comment]
I can see it here, but it still disappears...

**Comment by XDynames** [comment]
I’ll have to wait till I get in front of a computer and I’ll push a fix for you when I get to the bottom of it

**Comment by NIES-Tsuda** [comment]
Thanks for your time!

**Comment by XDynames** [comment]
So not sure if this will fix it or not but I have changed the version in `setup.sh` to one listed in your post above as available.

On my end the original version specified still had binaries for linux, windows and macos so I haven't been able to recreate the issues you are having, so I don't know if it is a fix or not. But pull the latest from main and give it a go.

**Comment by NIES-Tsuda** [comment]
XDynames.
Thanks for working on this so quickly!
I deleted the entire directory of StomaAI and ran the process again from the beginning,
I got the following error

ERROR: Could not find a version that satisfies the requirement torchvision=0.9.1+cpu (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2 0.2.2.post2, 0.2.2.post3, 0.12.0, 0.12.0+cpu, 0.12.0+cu102, 0.12.0+cu113, 0.12.0+cu115, 0.12.0+rocm4.3.1, 0.12.0+rocm4.5.2, 0.13.0, 0.13.0+ cpu, 0.13.0+cu102, 0.13.0+cu113, 0.13.0+cu116, 0.13.0+rocm5.0, 0.13.0+rocm5.1.1, 0.13.1, 0.13.1+cpu 116, 0.13.1+rocm5.0, 0.13.1+rocm5.1.1, 0.14.0, 0.14.0+cpu, 0.14.0+cu116, 0.14.0+cu117, 0.14.0+rocm5.1.1, 0.14.0+rocm5.2, 0.14.1, 0.14.1+cpu, 0.14.1 0.14.1+cu116, 0.14.1+cu117, 0.14.1+rocm5.1.1, 0.14.1+rocm5.2, 0.15.0, 0.15.0+cpu, 0.15.0+cu117, 0.15.0+cu118, 0.15.0+rocm5.3, 0.15.0+rocm5. 4.2, 0.15.1, 0.15.1+cpu, 0.15.1+cu117, 0.15.1+cu118, 0.15.1+rocm5.3, 0.15.1+rocm5.4.2)
ERROR: No matching distribution found for torchvision==0.9.1+cpu

Change the contents of 'setup.sh' to
torchvision==0.9.1+cpu
to
torchvision==0.14.1+cpu
I tried to rewrite the contents of 'setup.sh' from 'torchvision==0.9.1+cpu' to something like

I tried to do it, but it gave me the following error:
 setup.sh: line 13: syntax error: unexpected end of file

and since I worked on a Japanese system, it doesn't work at all, perhaps because of the garbled characters.
If I had more UNIX skills, I could fix it myself.

Translated with www.DeepL.com/Translator (free version)

**Comment by XDynames** [comment]
I have updated the version of torchvision but it will probably break again for torchaudio, let me know how it goes

**Comment by NIES-Tsuda** [comment]
XDynames.
Thanks again.
I guess torchaudio is still not working.
I got the following error.

ERROR: Could not find a version that satisfies the requirement torchaudio==0.8.1 (from versions: 0.11.0, 0.11.0+cpu, 0.11.0+cu102, 0.11.0+cu113, 0.11.0+cu115, 0.11.0+rocm4.3.1, 0.11.0+rocm4.5.2, 0.12.0, 0.12.0+cpu, 0.12.0+cu102, 0.12.0+cu113, 0.12.0+cu116, 0.12.0+rocm5.0, 0.12.0+rocm5.1.1, 0.12.1, 0.12.1+cpu, 0.12.1+cu102, 0.12.1+cu113, 0.12.1+cu116, 0.12.1+rocm5.0, 0.12.1+rocm5.1.1, 0.13.0, 0.13.0+cpu, 0.13.0+cu116, 0.13.0+cu117, 0.13.0+rocm5.1.1, 0.13.0+rocm5.2, 0.13.1, 0.13.1+cpu, 0.13.1+cu116, 0.13.1+cu117, 0.13.1+rocm5.1.1, 0.13.1+rocm5.2, 2.0.0, 2.0.0+cpu, 2.0.0+cu117, 2.0.0+cu118, 2.0.0+rocm5.3, 2.0.0+rocm5.4.2, 2.0.1, 2.0.1+cpu, 2.0.1+cu117, 2.0.1+cu118, 2.0.1+rocm5.3, 2.0.1+rocm5.4.2)
ERROR: No matching distribution found for torchaudio==0.8.1

**Comment by XDynames** [comment]
Hey sorry this took me awhile to get to, should be good to go now

**Comment by NIES-Tsuda** [comment]
XDynames.
Thanks for the bug fix.
I was even able to run the SAI without any errors.
Thank you so much!

**Comment by XDynames** [comment]
Awesome I’ll close this issue for now, let me know if you need anything else
