### ISSUE TITLE
CloudStor not available anymore.

### ISSUE THREAD

**Issue by totti0223** [XDynames/SAI-app#19]
Hi, all the data seems to be unaccessible due to cloudstor service stop.
Would be helpful if you can upload relavent files to another cloud storage.

https://support.aarnet.edu.au/hc/en-us/articles/6547542814095-What-happens-to-my-CloudStor-user-data-after-15-December-2023

**Comment by XDynames** [comment]
I have been perusing alternative hosting with my University but nothing has been a good fit so far. In the coming weeks I hope to have the file hosted privately to address these issues. I'll update when it is up.

**Comment by totti0223** [comment]
in case you have not considered yet. f.y.i.
i have been using figshare and the downloading speed as well as share link seems to work good for me.
e.g.
wget -O filename https://figshare.com/ndownloader/files/XXXXXXXX

**Comment by XDynames** [comment]
I did try Figshare awhile ago for a different project and got a little but frustrated by its lack of directory structure and how much information you have to add to even upload something, I'll have another look and see if it will suit this project. Thanks for the suggestion

**Comment by XDynames** [comment]
I have pushed a patch that changes the model and config hosting to Figshare, I haven't moved the images over yet, but the tool can be used for now
