### ISSUE TITLE
Issue with Streamlit

### ISSUE THREAD

**Issue by rolehir** [XDynames/SAI-app#21]
Hi,

I installed SAI on my computer, following your recommandations. Everything seemed to work correctly but when I tried to access the streamlit I got an error message of this type: 

"ImportError: libGL.so.1: cannot open shared object file: No such file or directory" 

and the following lines of error:
"File "/home/rolehir/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "/home/rolehir/SAI-app/main.py", line 3, in <module>
    from interface import ui
File "/home/rolehir/SAI-app/interface/ui.py", line 7, in <module>
    from .upload_single import display_upload_image
File "/home/rolehir/SAI-app/interface/upload_single.py", line 8, in <module>
    from tools.load import decode_downloaded_image
File "/home/rolehir/SAI-app/tools/load.py", line 10, in <module>
    import cv2
File "/home/rolehir/.local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
File "/home/rolehir/.local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)"

I am not used to work with this kind of code. Could you help me with this issue?

Thanks in advance
Best,
Rozenn

**Comment by XDynames** [comment]
Looks like your environment is missing LibGL which opencv needs. What operating system are you on?

**Comment by rolehir** [comment]
I am on windows 10 pro.

Rozenn

De : James Bockman ***@***.***>
Envoyé : mercredi 7 février 2024 08:29
À : XDynames/SAI-app ***@***.***>
Cc : Rozenn Le-Hir ***@***.***>; Author ***@***.***>
Objet : Re: [XDynames/SAI-app] Issue with Streamlit (Issue #21)


Looks like your environment is missing LibGL which opencv needs. What operating system are you on?

**Comment by XDynames** [comment]
I had a poke around and maybe using the command `sudo apt-get install libgl1` in your WSL terminal will install LibGL but there maybe other dependancies missing. I'm just going off this post [here](https://stackoverflow.com/questions/64664094/i-cannot-use-opencv2-and-received-importerror-libgl-so-1-cannot-open-shared-obj)

**Comment by rolehir** [comment]
I just tried and it worked perfectly. Thanks a lot for solving this issue.


Best,


Rozenn

________________________________
De : James Bockman ***@***.***>
Envoyé : jeudi 8 février 2024 07:26:13
À : XDynames/SAI-app
Cc : Rozenn Le-Hir; Author
Objet : Re: [XDynames/SAI-app] Issue with Streamlit (Issue #21)


I had a poke around and maybe using the command sudo apt-get install libgl1 in your WSL terminal will install LibGL but there maybe other dependancies missing. I'm just going off this post here<https://stackoverflow.com/questions/64664094/i-cannot-use-opencv2-and-received-importerror-libgl-so-1-cannot-open-shared-obj>
