### ISSUE TITLE
Lacks an .png

### ISSUE THREAD

**Issue by guiledau** [XDynames/SAI-app#4]
Apparently there is a .png lacking, which calls an error that does not allow the app to initialize.

 <img class="logo-img" src="data:image/png;base64,{base64.b64encode(open('logos/sai.png', "rb").read()).decode()}">
FileNotFoundError: [Errno 2] No such file or directory: 'logos/sai.png'

**Comment by XDynames** [comment]
Good catch - must have gotten lost when I reset the tree. I will add this back

**Comment by guiledau** [comment]
Thank you! I`ll try to use it on some tomato images I got and compare them with my results. Hope it works well in the tomato stomata too. It is a very interesting and helpful tool. Good luck!

**Comment by XDynames** [comment]
Okay should be added in the latest commit. Let me know if there are any other issues
