### ISSUE TITLE
Empty intersections when uploading samples

### ISSUE THREAD

**Issue by Mitsushima1** [XDynames/SAI-app#9]
I am using CPU mode. It calls an error when my uploading file to the app, as following:

2023-01-10 02:02:39.999 Uncaught app exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/ubuntu/SAI-app/main.py", line 38, in <module>
    main()
  File "/home/ubuntu/SAI-app/main.py", line 16, in main
    maybe_do_inference()
  File "/home/ubuntu/SAI-app/app/inference.py", line 58, in maybe_do_inference
    maybe_do_single_image_inference()
  File "/home/ubuntu/SAI-app/app/inference.py", line 71, in maybe_do_single_image_inference
    predictions, valid_indices = predictions_to_list_of_dictionaries(
  File "/home/ubuntu/SAI-app/app/inference.py", line 259, in predictions_to_list_of_dictionaries
    predictions = [
  File "/home/ubuntu/SAI-app/app/inference.py", line 260, in <listcomp>
    predictions_to_dictionary(i, predictions, n_stoma, valid_indices)
  File "/home/ubuntu/SAI-app/app/inference.py", line 281, in predictions_to_dictionary
    pred_CD = find_CD(pred_polygon, pred_AB)
  File "/home/ubuntu/SAI-app/app/inference.py", line 400, in find_CD
    if len(intersections) > 2:
TypeError: object of type 'MultiPoint' has no len()

**Comment by XDynames** [comment]
I will have to take a more detailed look at this but I think this is due to some changes in the shapely packages API I have been meaning to update for a little while that probably come how to roost now they’ve moved to version 2.0

As an interim solution rolling back the shapely version to a 1.* version

**Comment by XDynames** [comment]
On my data shapely 2.0 is still working, do you mind sending me a link to sample of your data for me to try?

**Comment by Mitsushima1** [comment]
> 

Sure, many thanks. Here's the link http://43.136.114.215:8501/.

**Comment by Mitsushima1** [comment]
> I will have to take a more detailed look at this but I think this is due to some changes in the shapely packages API I have been meaning to update for a little while that probably have come home to roost now they’ve moved to version 2.0
> 
> As an interim solution you can roll back the shapely version to a 1.* release

It works for me. I roll back shapely version to 1.6.1. No error any more. Thanks!

**Comment by XDynames** [comment]
Just edit that link out of your reply - looks like it is working
If you are using are downloading the images from that tab they will be low resolution compared to the original samples
If you want to test some samples you can try these from our validation set:
- Barley: https://cloudstor.aarnet.edu.au/plus/s/phlJcZkgS9y0fZd/download
- Arabidopsis: https://cloudstor.aarnet.edu.au/plus/s/u3vy3YsGemQKgIJ/download

**Comment by Mitsushima1** [comment]
> 

I will try these sample, many thanks!

**Comment by XDynames** [comment]
I have added the links to the README for others to use, thanks for using SAI

**Comment by Mitsushima1** [comment]
I met a new issue. There's no error when analyzing sample with low resolution. But when I tried to analyze sample from the two links provided in README, the streamlit got killed without exception printed:

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/68367198/211468476-953ce2bf-9dec-4c93-8b31-2307649a9d73.png">

**Comment by XDynames** [comment]
What OS are you using?
It could be due to the process running out of RAM, how much do you have installed?

**Comment by Mitsushima1** [comment]
> What OS are you using? It could be due to the process running out of RAM, how much do you have installed?

Ubuntu 20.04 LTS. It could be the reason as you mentioned, I am using a light house ECS for a quick demo.

**Comment by XDynames** [comment]
I have seen it use about 5GBs in the past for Barley images in batch mode, but it will depend primarily on input resolution

**Comment by Mitsushima1** [comment]
> I have seen it use about 5GBs in the past for Barley images in batch mode, but it will depend primarily on input resolution

Thanks for the suggestion, I run the newest commit locally on my computer, it runs smoothly. I think your assumption about the RAM is right. Here's my OS: Ubuntu 22.04 LTS. Thank you so much!
